# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fenix' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Fenix
     pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'DevSupport',
      'RCTNetwork',
      'RCTImage',
      'RCTWebSocket',
      'RCTGeolocation',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTActionSheet'
    ]
    pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'

    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

    pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

    pod 'react-native-maps', :path => '../node_modules/react-native-maps'

    pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'  # Uncomment this line if you want to support GoogleMaps on iOS
    pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
    pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS
    pod 'RNSnackbar', :path => '../node_modules/react-native-snackbar'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'react-native-wkwebview', :path => '../node_modules/react-native-wkwebview-reborn'

    pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'


  target 'FenixTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Fenix-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Fenix-tvOS

  target 'Fenix-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end